### ISSUE TITLE
YouTube lazy load

### ISSUE THREAD

**Issue by qertis** [tewst/landing-page#20]
Сейчас видео загружаются со старта страницы. Они доодны загружаться только если пользователь проскролил до нужного содердимого

**Comment by baskovsky** [comment]
Смержить https://gist.github.com/baskovsky/fba6e83899ea8ddc84b22078ef64777d

**Comment by qertis** [comment]
Было:
74 реквеста
Загружалось 5 сек

Стало:
43 реквеста
Загружается 2 сек

c73834034e0ef33957cddb638f2e1cabad5a6ff4
