### ISSUE TITLE
Добавить меты

### ISSUE THREAD

**Issue by baskovsky** [tewst/landing-page#21]
meta name="google-play-app" content="app-id=ru.newsmediamobile.lifenews"

 meta name="twitter:card" content="summary_large_image"
 meta name="twitter:site" content="@LifeislifeRu"
 meta name="twitter:creator" content="@LifeislifeRu"
 meta name="twitter:title" content="Кто заплатит &#34;налог на Google&#34;?"
 meta name="twitter:description" content="Лайф разобрался с тем, кому поможет и кто в реальности заплатит новый налог на цифровой контент, начинающий действовать 1 января 2017 года."
meta name="twitter:image" content="https://static.life.ru/posts/2016/12/947839/gr/north/e01af3b4648074ee0990bb640cc53d5d__1200x630.jpg"

meta property="og:locale:locale" content="ru_ru"

link rel="image_src" href="https://static.life.ru/posts/2016/12/947839/gr/north/e01af3b4648074ee0990bb640cc53d5d__1200x630.jpg"

Также добавить новые свойства в манифест 
https://life.ru/manifest.json

**Comment by qertis** [comment]
c711cc803643aaa625cc0da807686aa882a6ac02
